<a href="https://colab.research.google.com/github/coder178/ML_Sem6/blob/main/ML_Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch

In [ ]:
#single feature x,target,prediction,feature,byes
# generate model

# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

#temperature
inputs=np.array([[73],
[91],
[87],
[102],
[69]], dtype='float32') 

# taking random values(theta1)
weight = np.array([[12],
[21],
[18],
[32],
[25]], dtype='float32')

#bias
bias = np.array([[1],[1],[1],[1],[1]],dtype='float32')

# Generate predictions

prediction = (inputs*weight) + bias

print(prediction)
MSE=np.square(np.subtract(targets,prediction)).mean()

print(MSE)


[[ 877.]
 [1912.]
 [1567.]
 [3265.]
 [1726.]]
3854896.8


In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')
# Target (apples)
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')
from torch.utils.data import TensorDataset,DataLoader
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# print(inputs)
# print(targets)
dataset = TensorDataset(inputs,targets)
# print(dataset[:5])
#divide datasets into batches
train_loader = DataLoader(dataset, batch_size=4, shuffle=True)
# tuple(train_loader)

# generate random values with ean 0 and variance 1
weights= torch.randn(1,3, requires_grad=True)
biass = torch.randn(1, requires_grad=True)

# print(weights)
# print(biass)

def model(X):
  return X @ weights.t() + biass  # '@' - for matrix multiplication

def MSE_loss(predictions, targets):
  diff = predictions - targets
  return torch.sum(diff * diff)/diff.numel() #numel return number of elements in tensor

for x,y in train_loader:
    predictions = model(x)
    print("Prediction is:\n",predictions)
    print("\Actual target is:\n",y)
    print("\nLoss is: ",MSE_loss(predictions,y))

  #training the model
epochs = 100
for i in range(epochs):
  for x,y in train_loader:
    pds = model(x)

    loss = MSE_loss(pds,y)
    loss.backward()
    # Let's update the weights
    with torch.no_grad():
        weights -= weights.grad *1e-5
        biass -= biass.grad * 1e-5
        # Set the gradients to zero
        weights.grad.zero_()
        biass.grad.zero_()
print("Loss: ",loss)

for x,y in train_loader:
  preds= model(x)
  print("\nFinal Prediction is :\n",preds)
  print("\nActual targets are :\n",y)
  break
    



Prediction is:
 tensor([[-95.0942],
        [-51.3958],
        [-38.6394],
        [-11.8155]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[119.],
        [ 81.],
        [ 56.],
        [ 22.]])

Loss is:  tensor(18366.2695, grad_fn=<DivBackward0>)
Prediction is:
 tensor([[-62.2070]], grad_fn=<AddBackward0>)
\Actual target is:
 tensor([[103.]])

Loss is:  tensor(27293.3633, grad_fn=<DivBackward0>)
Loss:  tensor(1.2452, grad_fn=<DivBackward0>)

Final Prediction is :
 tensor([[ 99.1742],
        [ 25.4736],
        [ 57.7655],
        [114.8558]], grad_fn=<AddBackward0>)

Actual targets are :
 tensor([[103.],
        [ 22.],
        [ 56.],
        [119.]])


# **LAB 4_1**

In [ ]:
# Import Numpy & PyTorch
import numpy as np
import torch
import torch.nn as nn
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]],dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
# Define dataset
train_ds = TensorDataset(inputs,targets)

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)
next(iter(train_dl))

# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

# Define loss function
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

#definr utility function to train the model
def fit(num_epochs,model,loss_fn,opt):
  for epochs in range(num_epochs):
    for xb,yb in train_dl:
      #generate prediction
      pred = model(xb)
      loss = loss_fn(pred, yb)
      #perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
  print('Training loss: ', loss_fn(model(inputs), targets))
# Train the model for 100 epochs
fit(100, model, loss_fn, opt)






Parameter containing:
tensor([[0.0368, 0.4942, 0.0673],
        [0.4179, 0.2445, 0.0446]], requires_grad=True)
Parameter containing:
tensor([ 0.2997, -0.2302], requires_grad=True)
tensor(1569.0725, grad_fn=<MseLossBackward0>)
Training loss:  tensor(31.5979, grad_fn=<MseLossBackward0>)


In [ ]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704],
        [ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704],
        [ 58.1299,  71.6908],
        [ 79.8473,  97.5189],
        [121.8190, 136.9782],
        [ 26.6430,  45.5945],
        [ 94.6789, 108.6704]], grad_fn=<AddmmBackward0>)

In [ ]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# **Exercise 1:**
Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want).

In [1]:
import numpy as np
import torch
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [2]:
# Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)
# Compute gradients
print("Gradient :",output.backward())
# Gradients for weights
print(w)
print(w.grad)
# Gradients for bias
print(b)
print(b.grad)
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)
# Train for 100 epochs
for i in range(100):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([[-0.0984,  0.6823, -1.8431]], requires_grad=True)
tensor([0.7669], requires_grad=True)
Prediction : tensor([[-39.9561],
        [-66.1046],
        [-23.2683],
        [-48.1246],
        [-69.5410]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor([17155.0898], grad_fn=<DivBackward0>)
Gradient : None
tensor([[-0.0984,  0.6823, -1.8431]], requires_grad=True)
tensor([[-20730.6758, -23207.0020, -14585.9385]])
tensor([0.7669], requires_grad=True)
tensor([-251.1978])
tensor([[ 0.1089,  0.9143, -1.6973]], requires_grad=True)
tensor([0.7694], requires_grad=True)
New Loss : tensor([7457.9375], grad_fn=<DivBackward0>)
tensor([353.6365], grad_fn=<DivBackward0>)


Exercise 2: Try Linear regression on same prediction data using Tensorflow.

In [3]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [4]:
def model1(x):
  return x @ w.t() +b
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)
print(w)
print(w.grad)
print(b)
print(b.grad)
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

Prediction : tensor([[ 60.0060],
        [ 70.0219],
        [141.8410],
        [ 35.4202],
        [ 72.5074]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
Loss : tensor(353.6365, grad_fn=<MseLossBackward0>)
tensor([[ 0.1195,  1.4335, -1.0590]], requires_grad=True)
tensor([[ 218.1864,    5.1186, -337.4004]])
tensor([0.7736], requires_grad=True)
tensor([-0.4814])
tensor([234.3568], grad_fn=<DivBackward0>)
