<a href="https://colab.research.google.com/github/coder178/ML_Sem6/blob/main/ML_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [ ]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
weather_encoded=le.fit_transform(weather)
print("Weather:" ,weather_encoded)
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Weather: [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(weather_encoded,temp_encoded))
print("Features:",features)

Features: ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [ ]:
#Predict Output
predicted= model.predict([[0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[0,1]]) # 0:Overcast, 1:Hot
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
predicted= model.predict([[0,0]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


1.5 Exercise: Manually calculate output for the following cases and compare it
with system’s output.


1.5.1 (1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?

In [ ]:
predicted= model.predict([[0,1]]) # 0:overcast, 1:hot
print("Predicted Value:", predicted)

Predicted Value: [1]


(2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted= model.predict([[2,2]]) # 2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]


Gaussian Naive Bayes from datsets


In [ ]:
#Import scikit-learn dataset library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
#Load dataset
iris = datasets.load_iris()

In [ ]:
# print the names of the 13 features
print("Features: ", iris.feature_names)
# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


In [ ]:
# print data(feature)shape
print("\nData shape: ",iris.data.shape)
#print data(target)shape
print("\nTraget shape: ",iris.target.shape)
# print("\nData: ",iris.data)
# print("\nTarget: ",iris.target)
print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]
# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)
#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)


Data shape:  (150, 4)

Traget shape:  (150,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (100, 4)

New Traget shape:  (100,)


In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.30, random_state = 5)

In [ ]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
iris.target, test_size = 0.30, random_state = 10)

In [ ]:
import numpy as np
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
# from sklearn.metrics import confusion_matrix
metrics.confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/datasets/Dataset2.csv')
print("\nData :\n",data)


Data :
    Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [ ]:
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
Outlook_encoded=le.fit_transform(data.Outlook)
print("Outlook:" ,Outlook_encoded)
Temp_encoded=le.fit_transform(data.Temp)
print("Temp:",Temp_encoded)
Wind_encoded=le.fit_transform(data.Wind)
print("Wind:" ,Wind_encoded)
Humidity_encoded=le.fit_transform(data.Humidity)
print("Humidity:" ,Humidity_encoded)
Class_encoded=le.fit_transform(data.Class)
print("Class:" ,Class_encoded)

Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]
Temp: [1 1 1 2 2 2 0 0 0 2 2 2 1 2]
Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]
Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]
Class: [0 0 1 0 1 1 1 1 1 1 1 1 1 0]


In [ ]:
#Combinig weather and temp into single listof tuples
features=tuple(zip(Outlook_encoded,Temp_encoded,Wind_encoded,Humidity_encoded))
print("Features:",features)

Features: ((1, 1, 0, 2), (1, 1, 1, 0), (0, 1, 0, 2), (2, 2, 0, 2), (2, 2, 0, 2), (2, 2, 1, 1), (0, 0, 1, 2), (1, 0, 0, 2), (1, 0, 0, 1), (2, 2, 0, 0), (1, 2, 1, 0), (0, 2, 1, 1), (0, 1, 0, 2), (2, 2, 1, 2))


In [ ]:
#Create a Classifier
model=MultinomialNB()
# Train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [ ]:
#Predict Output
predicted= model.predict([[1,2,1,2]]) #outlook:rainy:1 temperature:mild:2 wind:false:0 humidity:normal:2 
print("Predicted Value:", predicted)

Predicted Value: [1]


In [ ]:
#Predict Output
predicted= model.predict([[2,0,1,0]]) #outlook:sunny:2 temperature:mild:0 wind:true:1 humidity:high:0 
print("Predicted Value:", predicted)

Predicted Value: [0]


In [ ]:
#Predict Output
predicted= model.predict([[1,1,0,2]]) # 0:Overcast, 2:Mild
print("Predicted Value:", predicted)

In [ ]:
dt=pd.read_csv('/content/drive/MyDrive/datasets/Dataset2.csv')
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
Outlook_encoded=le.fit_transform(dt.Outlook)
print("Outlook:" ,Outlook_encoded)
Temp_encoded=le.fit_transform(dt.Temp)
print("Temp:",Temp_encoded)
Wind_encoded=le.fit_transform(dt.Wind)
print("Wind:" ,Wind_encoded)
Humidity_encoded=le.fit_transform(dt.Humidity)
print("Humidity:" ,Humidity_encoded)
Class_encoded=le.fit_transform(dt.Class)
print("Class:" ,Class_encoded)
#Combinig weather and temp into single listof tuples
features=tuple(zip(Outlook_encoded,Temp_encoded,Wind_encoded,Humidity_encoded))
print("Features:",features)


Outlook: [1 1 0 2 2 2 0 1 1 2 1 0 0 2]
Temp: [1 1 1 2 2 2 0 0 0 2 2 2 1 2]
Wind: [0 1 0 0 0 1 1 0 0 0 1 1 0 1]
Humidity: [2 0 2 2 2 1 2 2 1 0 0 1 2 2]
Class: [0 0 1 0 1 1 1 1 1 1 1 1 1 0]
Features: ((1, 1, 0, 2), (1, 1, 1, 0), (0, 1, 0, 2), (2, 2, 0, 2), (2, 2, 0, 2), (2, 2, 1, 1), (0, 0, 1, 2), (1, 0, 0, 2), (1, 0, 0, 1), (2, 2, 0, 0), (1, 2, 1, 0), (0, 2, 1, 1), (0, 1, 0, 2), (2, 2, 1, 2))


In [ ]:
#import the necessary module
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(features,Class_encoded, test_size = 0.25, random_state = 5)

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

Accuracy: 0.25


array([[0, 1],
       [2, 1]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.  0.5]
recall: [0.         0.33333333]


In [ ]:
data_train, data_test, target_train, target_test = train_test_split(features,Class_encoded, test_size = 0.20, random_state = 5)
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(target_test, target_pred))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.3333333333333333
[[0 1]
 [1 1]]
precision: [0.  0.5]
recall: [0.  0.5]
